apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-pyvvalgl
  janus-idp.io/tekton: go-pyvvalgl
  backstage.io/kubernetes-id: go-pyvvalgl
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-pyvvalgl
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
